curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_AMS-Regular.ttf -o KaTeX_AMS-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_AMS-Regular.woff -o KaTeX_AMS-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_AMS-Regular.woff2 -o KaTeX_AMS-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Caligraphic-Bold.ttf -o KaTeX_Caligraphic-Bold.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Caligraphic-Bold.woff -o KaTeX_Caligraphic-Bold.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Caligraphic-Bold.woff2 -o KaTeX_Caligraphic-Bold.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Caligraphic-Regular.ttf -o KaTeX_Caligraphic-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Caligraphic-Regular.woff -o KaTeX_Caligraphic-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Caligraphic-Regular.woff2 -o KaTeX_Caligraphic-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Fraktur-Bold.ttf -o KaTeX_Fraktur-Bold.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Fraktur-Bold.woff -o KaTeX_Fraktur-Bold.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Fraktur-Bold.woff2 -o KaTeX_Fraktur-Bold.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Fraktur-Regular.ttf -o KaTeX_Fraktur-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Fraktur-Regular.woff -o KaTeX_Fraktur-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Fraktur-Regular.woff2 -o KaTeX_Fraktur-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Bold.ttf -o KaTeX_Main-Bold.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Bold.woff -o KaTeX_Main-Bold.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Bold.woff2 -o KaTeX_Main-Bold.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-BoldItalic.ttf -o KaTeX_Main-BoldItalic.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-BoldItalic.woff -o KaTeX_Main-BoldItalic.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-BoldItalic.woff2 -o KaTeX_Main-BoldItalic.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Italic.ttf -o KaTeX_Main-Italic.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Italic.woff -o KaTeX_Main-Italic.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Italic.woff2 -o KaTeX_Main-Italic.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Regular.ttf -o KaTeX_Main-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Regular.woff -o KaTeX_Main-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Main-Regular.woff2 -o KaTeX_Main-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Math-BoldItalic.ttf -o KaTeX_Math-BoldItalic.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Math-BoldItalic.woff -o KaTeX_Math-BoldItalic.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Math-BoldItalic.woff2 -o KaTeX_Math-BoldItalic.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Math-Italic.ttf -o KaTeX_Math-Italic.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Math-Italic.woff -o KaTeX_Math-Italic.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Math-Italic.woff2 -o KaTeX_Math-Italic.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Bold.ttf -o KaTeX_SansSerif-Bold.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Bold.woff -o KaTeX_SansSerif-Bold.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Bold.woff2 -o KaTeX_SansSerif-Bold.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Italic.ttf -o KaTeX_SansSerif-Italic.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Italic.woff -o KaTeX_SansSerif-Italic.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Italic.woff2 -o KaTeX_SansSerif-Italic.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Regular.ttf -o KaTeX_SansSerif-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Regular.woff -o KaTeX_SansSerif-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_SansSerif-Regular.woff2 -o KaTeX_SansSerif-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Script-Regular.ttf -o KaTeX_Script-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Script-Regular.woff -o KaTeX_Script-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Script-Regular.woff2 -o KaTeX_Script-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size1-Regular.ttf -o KaTeX_Size1-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size1-Regular.woff -o KaTeX_Size1-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size1-Regular.woff2 -o KaTeX_Size1-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size2-Regular.ttf -o KaTeX_Size2-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size2-Regular.woff -o KaTeX_Size2-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size2-Regular.woff2 -o KaTeX_Size2-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size3-Regular.ttf -o KaTeX_Size3-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size3-Regular.woff -o KaTeX_Size3-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size3-Regular.woff2 -o KaTeX_Size3-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size4-Regular.ttf -o KaTeX_Size4-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size4-Regular.woff -o KaTeX_Size4-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Size4-Regular.woff2 -o KaTeX_Size4-Regular.woff2
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Typewriter-Regular.ttf -o KaTeX_Typewriter-Regular.ttf
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Typewriter-Regular.woff -o KaTeX_Typewriter-Regular.woff
curl https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/fonts/KaTeX_Typewriter-Regular.woff2 -o KaTeX_Typewriter-Regular.woff2