-- AlterTable
ALTER TABLE "ask_answer" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "question_uuid" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "ask_answer_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "ask_question" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "ask_question_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "blog" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "title" SET NOT NULL,
ALTER COLUMN "description" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "blog_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "book_chapter" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "book_uuid" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "book_chapter_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "book_meta" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "book_meta_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "book_sentence" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "chapter_uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "sentence_type" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "book_sentence_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "listen_media" ALTER COLUMN "note" SET NOT NULL;

-- AlterTable
ALTER TABLE "listen_tag" ALTER COLUMN "description" SET NOT NULL;

-- AlterTable
ALTER TABLE "qsa_card" ALTER COLUMN "user_id" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "qsa_card_tag" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "qsa_tag" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "qsa_tag_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "voice_access_command" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "user_id" SET NOT NULL,
ALTER COLUMN "action_uuid" SET NOT NULL,
ALTER COLUMN "language" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "voice_access_command_pkey" PRIMARY KEY ("uuid");

-- AlterTable
ALTER TABLE "word_trash" ALTER COLUMN "uuid" SET NOT NULL,
ALTER COLUMN "created_at" SET NOT NULL,
ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updated_at" SET NOT NULL,
ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP,
ADD CONSTRAINT "word_trash_pkey" PRIMARY KEY ("uuid");

